### PR TITLE
Fix and improve the bump_version tool

### PR DESCRIPTION
**Pull request by SVilgelm**
Fix incorrect sorting.
Add new flags to smake this tool more flexible.

### CODE REVIEW

**Comment by Nerzal** [comment]
The tool is so nice. Have you thought about creating a new repository for this tool?
I bet many people would like that :D

**Comment by Nerzal** [comment]
Or even better - you could try to propose it as an official go tool

**Comment by SVilgelm** [comment]
@Nerzal Here it is: https://github.com/SVilgelm/bumpversion :-)
I don't think it is possible to propose it as an official go tool, but will see

**Comment by Nerzal** [comment]
nice one :D

**Pull request merged**
