### PR TITLE
add support for Client Scope Scope Mappings

### PR DESCRIPTION
**Pull request by bakito**
I currently have the usecase, where I need to be able to check and update Client Scope Scope Mappings . See https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_scope_mappings_resource

This PR implements the missing functions that  I'd need to fulfill my tasks.

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi! Thank u for your contribution! 
All in all it looks good, could you please also add the new functions to the readme? :) 
And also adding new test functions for these tests would be nice.

I currently try to figure out, why the tests run perfectly fine locally but fail in the pipeline.

**Comment by bakito** [comment]
I was also not able to get the tests running locally, hence I'm having problems on writing tests.

**Comment by Nerzal** [comment]
thank you for the contribution :) 
Could you please resolve the merge conflicts? :)

**Comment by Nerzal** [comment]
LGTM, now merging. 
But it will take a day or two until i release a new tag. Want to fix the test pipelines again

**Pull request merged**
