### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by kisamoto**
README updated with latest docker image hosted on Quay.io and short instructions on tearing down container after tests have completed

### CODE REVIEW

**Comment by SVilgelm** [comment]
Thank you for your efforts, but there is a question - why do we need to use the `quay.io`? What is wrong with docker hub? I haven't found `quay.io` in the Keycloak's documentation.

**Comment by kisamoto** [comment]
Ah this is because earlier in the year the [mailing list](https://lists.jboss.org/pipermail/keycloak-user/2019-March/017456.html) eluded to moving to Quay.io as their main source of Docker images. Currently Docker Hub is still being pushed to for backwards compatibility but I believe Quay.io will become the primary source for Keycloak Docker images.

**Comment by SVilgelm** [comment]
thank you, if so then we also need to update the `.travis.yml` to use `quay.io`: https://github.com/Nerzal/gocloak/blob/master/.travis.yml#L29
Can you do it?

**Comment by Nerzal** [comment]
Thanks again <3

**Pull request merged**
