### PR TITLE
fix(model): wrong value type

### PR DESCRIPTION
**Pull request by r3st**
Fixed wrong type in models.go as described in #387

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi do you know if this was a change in between different keycloak versions, or was the model wrong all the time? :D

**Comment by r3st** [comment]
> Hi do you know if this was a change in between different keycloak versions, or was the model wrong all the time?

I will check this, but when it happens before v15 of keycloak.

**Comment by r3st** [comment]
Since 8 Years no change was made to this field, so I think the model was all time wrong.

https://github.com/keycloak/keycloak/blame/main/core/src/main/java/org/keycloak/representations/idm/ClientRepresentation.java#L65

**Comment by Nerzal** [comment]
Thank you for checking! 
And thank you for the contribution, i'll merge this now :)

**Pull request merged**
