### PR TITLE
Remove .travis.yml

### PR DESCRIPTION
**Pull request by SVilgelm**
Since we are testing the changes using github actions we don't need the .travis.yml anymore.

### CODE REVIEW

**Comment by SVilgelm** [comment]
@Nerzal please remove `Travis CI` as a required check in branch settings.

**Comment by SVilgelm** [comment]
@Nerzal, the codecove doesn't work because no token. Could you copy your token from codecove (https://docs.codecov.io/v4.3.0/docs/about-the-codecov-bash-uploader) and create a `CODECOV_TOKEN` secret in settings.

**Comment by Nerzal** [comment]
i guess your last comment is now obsolete, as it looks like you find the token? :D

**Comment by SVilgelm** [comment]
No, you need to take your token, it works, because we still have Travis CI

**Comment by Nerzal** [comment]
i added the token to the secrets

**Comment by SVilgelm** [comment]
@Nerzal please remove Travis CI - Pull Request  as required job in settings

**Comment by Nerzal** [comment]
done

**Comment by SVilgelm** [comment]
Hmm, it doesn't work. GitHub help says "Secrets are not passed to workflows that are triggered by a pull request from a fork."
We need to wait the https://github.com/codecov/codecov-action/issues/29 is resolved

**Comment by SVilgelm** [comment]
Temporary solution - uploading codecov report only from push event in main repo, it prevents the failed tests in fork repos

**Comment by Nerzal** [comment]
feels like a dirty hack, but better than waiting till they implement the token less upload

**Comment by SVilgelm** [comment]
Agree, but actually this report on pull requests does nothing :)

**Comment by Nerzal** [comment]
so i guess i just use admin permissions and merge it? :D

**Comment by SVilgelm** [comment]
it's better if you remove the codecov as required checks, so I also can merge other PRs

**Comment by Nerzal** [comment]
tada

**Comment by Nerzal** [comment]
before u merge, lemme test another thing using this pr ^^

**Comment by SVilgelm** [comment]
nice :)

**Comment by SVilgelm** [comment]
sure

**Comment by Nerzal** [comment]
okay i'm done.

**Pull request merged**
