### PR TITLE
Extend ClearCache and add benchmarks for Login

### PR DESCRIPTION
**Pull request by SVilgelm**
* Update tests
Added ClearUserCache and ClearKeysCache functions and call them in tests.
Added benchmark tests for Login.
Remove `FailIf` and `FailIfErr` functions in favor of `assert.False` and `assert.NoError` functions. The `assert` functions provides better error messages.

* Using  GitHub Action to run all tests instead of Triavis-CI
Added `workflows/go.yml` 
Using `golangci-lint` to check a style.
Running `Nancy` for dependencies.
Running unit tests with benchmarks.
Publish benchmarks to the `gh-pages` branch.

* Updating README
Added tag badge.
Using GitHub badge for Build Status instead of Travis.
Added link for the benchmarks page: https://nerzal.github.io/gocloak/dev/bench

### CODE REVIEW

**Comment by SVilgelm** [comment]
I'm still working on it, it continues to fail, just little later now :(

**Comment by Nerzal** [comment]
How do you test these github actions stuff? :D

**Comment by SVilgelm** [comment]
@Nerzal, It's easy. The actions can be tested on any fork: https://github.com/SVilgelm/gocloak/actions

**Comment by Nerzal** [comment]
Okay nice, so what exactly was missing on this one? 
Or am i just confused? :D

**Comment by SVilgelm** [comment]
There is an issue with tests. If I run `go test` several times in a row, then it fails on 4th or 5th run. Something modifies the env. I tried to fix this issue, but unsuccessfully. Will take a look later

**Comment by SVilgelm** [comment]
I will create and issue, maybe someone can fix it.

**Comment by Nerzal** [comment]
Okay, if it is in the 4th or 5th run, i'm fine with merging and fixing afterwards

**Comment by SVilgelm** [comment]
hmmm :) I cannot approve my PR, but it requires two approvals to be merged. So, @Nerzal please merge ti

**Pull request merged**
