### PR TITLE
#160 added support for user federated identities

### PR DESCRIPTION
**Pull request by awltr**
Issue https://github.com/Nerzal/gocloak/issues/160

### CODE REVIEW

**Comment by awltr** [comment]
I don't know why the tests failed. Locally my new test was executed successfully.

**Comment by SVilgelm** [comment]
@awltr there are several errors, they should be fixed in #162

**Comment by awltr** [comment]
@SVilgelm Okay. Do I have to do something or can you merge it yourself, if there are no other problems?

**Comment by SVilgelm** [comment]
@awltr the #162 is merged, could you rebase your PR and push it again, so we the check will be re-triggered with a new workflow

**Comment by awltr** [comment]
@SVilgelm done

**Pull request merged**
