### PR TITLE
Update models.go

### PR DESCRIPTION
**Pull request by pp010**
change `PublicClient` to `publicClient` to avoid bad request.

Please merge this with priority. 

Thanks for your contribution!
Hi, if there is an issue, that your PR adresses, please link it!

### CODE REVIEW

**Comment by Nerzal** [comment]
Damn omitempty! :D That's why the test is still green.

**Comment by SVilgelm** [comment]
yep, I think we need to carefully go through all representations and remove `omitempty` flag.

**Comment by Nerzal** [comment]
But most of these fields are optional, so removing this flag would create new errors when trying to create stuff

**Comment by SVilgelm** [comment]
That's also true :)

**Comment by pp010** [comment]
hi @Nerzal , could you please provide me write access so that i can add some attributes in `models.go` and raise a pull request? Currently i am unable to push anything from my codebase. If there is any other way to contibute, please let me know.

**Comment by SVilgelm** [comment]
@pp010 this works differently, you need to push your changes in new branch in your fork and send a PR from your branch in your fork to master branch in Nerzal's repo.

**Comment by Nerzal** [comment]
Hi @pp010 it works exactly the way @SVilgelm mentioned.
I'll look forward to your contribution :)

**Pull request merged**
