### PR TITLE
Add token exchange, and method of getting custom claims

### PR DESCRIPTION
**Pull request by lordmortis**
I'm not sure how to test the token exchange part of this, as it will require a keycloak server with a specific setup (for the moment) to work. 

We're using these in a project we are working on, so these methods have been tested in anger.

### CODE REVIEW

**Comment by Nerzal** [comment]
Why did you close this PR? :D

**Comment by lordmortis** [comment]
No tests yet :)

**Comment by Nerzal** [comment]
okay pretty good reason, but we could just let that one open till we have some

**Comment by SVilgelm** [comment]
If you need a specific configuration of a realm, so you can update the gocloak-realm.json file in the test data folder.

**Pull request closed without merging**
