### PR TITLE
GetComponentsWithParams and UpdateComponent added

### PR DESCRIPTION
**Pull request by Tolyar**
Thanks for your contribution!

There is two new methods.
1. GetComponentsWithParams() . According to keycloak's documentation GET /{realm}/components has some query parameters. I create new function to compatibility with old versions, because changing of GetComponents s bad idea.
2 UpdateComponent - allow to update exists component.

All new methods covered by tests.

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi, 

can you please run

> go fmt -w -s .

That should fix the pipeline :)

**Comment by Tolyar** [comment]
> 

Do you mean gofmt -w -s . ? Because go fmt does not support -s and -w flags. Problem that gofmt -w -s . do nothing in my branch. git diff show zero changes. I use go1.18.4

**Comment by Nerzal** [comment]
hmn does goftm ./... does anything ?

**Comment by Tolyar** [comment]
> hmn does goftm ./... does anything ?

Yes. I think this is because I've used gofumpt instead of gofmt as default formatter. Looks like gofmt thinks that all is ok but linter on github is don't. Another strange thing - I've enabled all actions from yours repo in my repo and all was passed before I've created PR.

**Comment by Tolyar** [comment]
> hmn does goftm ./... does anything ?

:) I found a problem. It is not code problem but actions. This is the error from linter

>Run cat test.log
cat: test.log: No such file or directory
Error: Process completed with exit code [1](https://github.com/Nerzal/gocloak/runs/7682602770?check_suite_focus=true#step:10:1).

**Comment by Tolyar** [comment]
I believe than problem fixed.

**Review by Nerzal — APPROVED** [review]

**Pull request merged**
