### PR TITLE
GroupList Retrieval by RoleName

### PR DESCRIPTION
**Pull request by krisztianganyi**
Our specific use case requires us to be able to retrieve a list of groups based on a RoleName we passed to our backend.
My modifications contain the necessary method to do so.

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi, thank you for the contribution! 
Can you try to merge in the current main branch? It looks like, your work is based on an old commit

**Comment by krisztianganyi** [comment]
Just updated the main from your branch onto my fork, Now only minor differences are present in the 2 files that are affected (basically it only contains what it should) !
Hope it's all right like this!

**Comment by krisztianganyi** [comment]
Hey, merged the latest version of your main to my fork, now it only contains a minimal amount of changes accross the 2 files.
Please take a look at it.
Thanks!

**Comment by Nerzal** [comment]
thanks for your contribution. 
LGTM now merging. 

Note: it will take some time until a new tag is being released due to broken pipelines and manual testing effort on my side.

**Pull request merged**
