### PR TITLE
Add DeleteIdentityProviderMapper and GetIdentityProviderMappers

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Hello!

This PR adds support for two new calls around identity provider mappers, along with test coverage.

Let me know if I can do anything to make this better and I will! 😄 

A huge thanks, as always, to this repo's maintainers. ❤️

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi thank u for your contribution! 
I'm sorry, that the CI pipeline was broken for such a long time. I was very busy @work + writing a book. 
I will dedicate my free time in the next week to fix that issues. 

As soon as the pipeline is fixed, i'll merge the PRs again. 
So - sorry and thank u!

**Comment by tyrannosaurus-becks** [comment]
@Nerzal oh no worries, I have myself maintained an open source repo before and I know how hard (and potentially draining) it can be. Just was posting the test to make it easy for you to look at down the road whenever. Thanks again for everything you do here! 😄

**Comment by Nerzal** [comment]
I have not perceived that comment on the test in any kind of dissatisfaction, so no worries, i just wanted to explain, why I have not been that active in the past weeks :)

**Comment by Nerzal** [comment]
Hi, 
can you please merge the main branch into your branch? :) 
I think i have worked around the Pipeline test fails.

**Review by Nerzal — APPROVED** [review]

**Comment by Nerzal** [comment]
Change is included in Tag v8.4.0
Thank you for your contribution :)

**Pull request merged**
