### PR TITLE
client: use `sync.Map` to store realm certificates

### PR DESCRIPTION
**Pull request by alexsn**

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi can you check, why the tests did fail, before we review that?

**Comment by SVilgelm** [comment]
@Nerzal it fails due to cache in the Keycloak

**Comment by alexsn** [comment]
> Hi, could you clarify why using the sync.Map is better in this case? It's already thread safe due to using the sync.Mutex.
> In your approach there is still using the mutex and sync.Map, so actually you will use two mutexes, one defined here and one or more from the sync.Map structure

The idea is to optimize the fast path (i.e. cache hit) which is the most common case and this is where `sync.Map.Load` is much faster than a mutex protected map read. Now the second mutex is there to prevent multiple goroutines from fetching certs and is the slow path that mostly occurs on startup.

**Comment by SVilgelm** [comment]
> The idea is to optimize the fast path (i.e. cache hit) which is the most common case and this is where `sync.Map.Load` is much faster than a mutex protected map read. Now the second mutex is there to synchronize cert fetching (i.e. doing http calls to keycloak) and is the slow path that mostly occurs on startup.

Ok I see, sync.Map uses the mutex only if the item is not stored in the read variable. So the question do we need to keep our mutex?

**Comment by alexsn** [comment]
> > The idea is to optimize the fast path (i.e. cache hit) which is the most common case and this is where `sync.Map.Load` is much faster than a mutex protected map read. Now the second mutex is there to synchronize cert fetching (i.e. doing http calls to keycloak) and is the slow path that mostly occurs on startup.
> 
> Ok I see, sync.Map uses the mutex only if the item is not stored in the read variable. So the question do we need to keep our mutex?

Yes we do as we need to handle the case where multiple goroutines have a cache miss (say on app start) and we only need one of them to populate the cache while others should wait. That's why the additional `.Load` call exists after acquiring the mutex (i.e. raced and lost the mutex and some other goroutine populated the cache).

**Comment by SVilgelm** [comment]
Release in `v7.4.0`

**Pull request merged**
