### PR TITLE
add support for tracing header injection

### PR DESCRIPTION
**Pull request by 2785**
Thanks for your contribution!
Hi, if there is an issue, that your PR adresses, please link it! 

issue: https://github.com/Nerzal/gocloak/issues/257

### CODE REVIEW

**Comment by 2785** [comment]
No clue how to make codebeat happy. 

Seems to be same unit test failure as master branch, also no clue how to make that happy :facepalm:

**Comment by 2785** [comment]
will give an attempt at fixing the test

**Comment by Nerzal** [comment]
fixing these tests would be greatly appreciated. 
I just had no time to check whats going on :(

**Comment by 2785** [comment]
this here is why they failing: https://www.keycloak.org/docs/latest/upgrading/#client-credentials-grant-without-refresh-token-by-default

tests pass on keycloak:10 and 11, fails on 12

**Comment by Nerzal** [comment]
Hi, you could try to update the branch with the current master branch :)

**Comment by 2785** [comment]
@Nerzal oooo is it fixed? The code in this PR also need some love, haven't gotten around to doing it. Can take a look today.

**Comment by Nerzal** [comment]
damnit, seems like i still need to put some love into the cI :(

**Comment by Nerzal** [comment]
Hi, 
can you please merge the main branch into your branch? :) 
I think i have worked around the Pipeline test fails.

**Comment by 2785** [comment]
@Nerzal hey, ye, I'll need to fix this branch too, some more code and tests need to go in, will remove the WIP when it's ready :)

**Comment by Nerzal** [comment]
Okay (:

**Comment by 2785** [comment]
@Nerzal  same nil pointer deref as on master, I'm a bit uncertain if we should bother writing tests for telemetry code, your call.

**Comment by Nerzal** [comment]
now merging

**Pull request merged**
