### PR TITLE
feat: add requiredActionProviderRepresentation

### PR DESCRIPTION
**Pull request by shibumi**
This commit adds the requiredActionProviderRepresentation and a function for updating required actions

### CODE REVIEW

**Comment by shibumi** [comment]
Code is tested and works for me

**Comment by Nerzal** [comment]
Hi, could you please also add a unit/integration test for that? :)

**Comment by shibumi** [comment]
@Nerzal yeah sure. Let me have a look on this :D

**Comment by Nerzal** [comment]
Thank you for the contribution! 
I'll do now merge. It might take a day or 2 until i release a new tag, as there is also a little breaking change in the pipeline. 

I'll create a new Release + Tag until that one is also merged.

**Pull request merged**
