### PR TITLE
Added APIs to support fine-grained authorization

### PR DESCRIPTION
**Pull request by dmartinol**
See issue #431

### CODE REVIEW

**Comment by dmartinol** [comment]
Hi, could anyone have a look at this PR?

**Comment by Nerzal** [comment]
The tests fail cause of a linter warning. 
Could you fix that?

**Comment by Nerzal** [comment]
Thank you for the contribution! 
Could you also add 1 test case per new function?

**Comment by dmartinol** [comment]
> Thank you for the contribution! Could you also add 1 test case per new function?

I added 2 and the coverage should increase, can you try?

**Review by Nerzal — APPROVED** [review]

**Comment by Nerzal** [comment]
LGTM, thank you for the contribution!

**Comment by dmartinol** [comment]
> LGTM, thank you for the contribution!

Thanks to you for maintaining this amazing client!
BTW: are you planning to create a new release soon, so we can integrate it in our application?

**Pull request merged**
