### PR TITLE
Edited "BaererOnly" parameter to "BearerOnly" as per Keycloak documentation

### PR DESCRIPTION
**Pull request by manju754**
Edited "BaererOnly" parameter to "BearerOnly" as per Keycloak documentation

Thanks for your contribution!
Hi, if there is an issue, that your PR adresses, please link it!

### CODE REVIEW

**Comment by manju754** [comment]
@SVilgelm Can you review and merge this PR

**Comment by Nerzal** [comment]
Hi, thx for the fix !

**Comment by SVilgelm** [comment]
@Nerzal please merge it

**Comment by SVilgelm** [comment]
No, you didn't, you just said "thx" :)

**Comment by SVilgelm** [comment]
I pushed a tag 2.0.1 with this commit

**Comment by Nerzal** [comment]
Yeah i was on my phone when trying to merge it :D

**Pull request merged**
