### PR TITLE
Fix wrong function signature

### PR DESCRIPTION
**Pull request by moritz-muecke**
Fixes an error in the function signature of the LoginClientTokenExchange implementation.

### CODE REVIEW

**Review by Nerzal — APPROVED** [review]
looks like it matches the signature defined in the interface now.
Thank you for the contribution.

**Comment by moritz-muecke** [comment]
As you merged this change into main and the pipeline seemed to run successfully, shouldn't there be a 9.0.2 already? @Nerzal

**Comment by Nerzal** [comment]
I was in the middle of a meeting. New tag is coming in some minutes.

**Comment by moritz-muecke** [comment]
Take your time. Wasn't aware of if this happens automatically or manually. Didn't want to stress you out :-)

**Comment by Nerzal** [comment]
No worries, new tag is released as v9.0.2 containing these changes.

**Pull request merged**
