### PR TITLE
Implement Credential APIs

### LINKED ISSUE #158: Get User Credentials API
**Is your feature request related to a problem? Please describe.**
Current there is no API to get user credentials

**Describe the solution you'd like**
API to get user credentials.

**Additional context**
Screenshot 2020-03-21 at 1 58 05 AM

```
curl 'https://SERVER/auth/admin/realms/{REALM}/users/{USERID}/credentials' 
```
RESPONSE:
```json
[{"id":"12296c78-b9ad-4ef4-a272-e801f8ae44a6","type":"password","createdDate":1584731908202,"credentialData":"{\"hashIterations\":27500,\"algorithm\":\"pbkdf2-sha256\"}"}]

### PR DESCRIPTION
**Pull request by SVilgelm**
fix #158

### CODE REVIEW

**Comment by SVilgelm** [comment]
@grizzly-monkey  please test it

**Comment by SVilgelm** [comment]
@Nerzal please review it

**Comment by grizzly-monkey** [comment]
Works well.

**Comment by SVilgelm** [comment]
@Nerzal could you review thus please?

**Comment by SVilgelm** [comment]
@Nerzal I need you here :-)

**Comment by Nerzal** [comment]
Sorry, merged :)

**Comment by Nerzal** [comment]
pushed Tag V5.4.0

**Pull request merged**
