### PR TITLE
Add params to GetUsersByRoleName

### PR DESCRIPTION
**Pull request by upils**
Add params to list more than a 100 users with GetUsersByRoleName

Fixing https://github.com/Nerzal/gocloak/issues/391

### CODE REVIEW

**Comment by upils** [comment]
Hi @Nerzal, is this possible to check this and let workflows run?

**Comment by Nerzal** [comment]
Hi, if you merge the main branch the tests should be able to run now :)

**Comment by upils** [comment]
Merge done, this should work now.

**Comment by upils** [comment]
I added a test to improve coverage.

I noticed the docker image used was keycloak:latest, which now points to `20.0.2`. They seems to have reworked the way UserInfo can be accessed (see https://github.com/keycloak/keycloak-documentation/commit/533b730bd42aefff29d255d6d5f01cdbb9e0dfe8) so both `GetUserInfo` and `GetRawUserInfo` are broken in this keycloak version. So I have pinned the keycloak version to 19.0. I can remove this if you prefer.

**Review by Nerzal — APPROVED** [review]
LGTM thank you for the contribution

**Pull request merged**
