### PR TITLE
WIP: Support for Keycloak 17+ / Version 19 as target

### PR DESCRIPTION
**Pull request by Nerzal**
WIP

Contains several breaking changes. 
Mostly due to keycloak changing things

## Fixes

Fixes: #358 
Fixes: #346
Fixes: #341

Introduced new functional option: 

`SetLegacyWildFlySupport()`

usage:

```
client := gocloak.NewClient("hostname", gocloak.SetLegacyWildFlySupport())
```

## Features

Implements: #331 

## Improvements:

Closes: #334

Renamed the following functions:

AddClientRoleToUser
AddClientRoleToGroup
DeleteClientRoleFromUser

to:

AddClientRolesToUser
AddClientRolesToGroup
DeleteClientRolesFromUser

The old functions are still in place but deprecated.

This Closes: #248

### CODE REVIEW

**Comment by jack-bischoff** [comment]
Hello,

My company is currently using this library and are interested in the status of this PR and what it means for the future of gocloak:
* Do you have an estimated timeline on when a you will cut a new release with keycloak 17+ support?
* I see that this particular PR will not work with Keycloak before version 17. Are there any plans to make gocloak v11+ backwards compatible at all?
* Is there anything we could do to assist? Testing, etc.?

Thank you for developing such a great library. We truly appreciate it

**Comment by Nerzal** [comment]
Hi  @jack-bischoff 

i need to find some time to fix the last issues here. 
1. Merge conflicts 
2. There are 11 failing test still on the dev-branch some of them might be tricky to fix

In general: when using the new functional option

 > SetLegacyWildFlySupport()

Most functionalities should still be compatible to older keycloak versions.
Determining, what stays compatible and what might not isn't done yet. 

I currently cannot give an estimation, when i'll be able to fix up the remaining tests.
If you want to help, feel free to fetch the dev branch and try to fix some, that would really help.

**Comment by p53** [comment]
@Nerzal hi i created pull request #367 to this dev branch, which fixes realm import, after that i see only these tests failing:

`    client_test.go:1073:                                                                                                                                                                     
                Error Trace:    /home/test/Software/gocloak/client_test.go:1073                                                                                                              
                Error:          Received unexpected error:                                                                                                                                   
                                403 Forbidden: access_denied: not_authorized
                Test:           Test_GetRequestingPartyToken                                  
                Messages:       Get requesting party token failed                                                                                                                            
--- FAIL: Test_GetRequestingPartyPermissionDecision (0.25s)                                   
    client_test.go:795:                     
                Error Trace:    /home/test/Software/gocloak/client_test.go:795                
                Error:          Received unexpected error:                                    
                                403 Forbidden: access_denied: not_authorized                  
                Test:           Test_GetRequestingPartyPermissionDecision
                Messages:       GetRequestingPartyPermissions failed   
--- FAIL: Test_RetrospectRequestingPartyToken (0.22s)                                         
    client_test.go:699:               
                Error Trace:    /home/test/Software/gocloak/client_test.go:699
                Error:          Received unexpected error:                                    
                                403 Forbidden: access_denied: not_authorized
                Test:           Test_RetrospectRequestingPartyToken
                Messages:       GetRequestingPartyToken failed                                
--- FAIL: Test_GetRequestingPartyPermissions (0.18s)                                          
    client_test.go:755:                                                                       
                Error Trace:    /home/test/Software/gocloak/client_test.go:755
                Error:          Received unexpected error:                                    
                                403 Forbidden: access_denied: not_authorized                  
                Test:           Test_GetRequestingPartyPermissions                            
                Messages:       GetRequestingPartyPermissions failed  `

**Comment by p53** [comment]
@Nerzal checked that first test  Test_GetRequestingPartyToken, but i am not sure about that process of getting RPT, as i know first ticket should be retrieved then with this ticket request made to get RPT, otherwise there should be 403

**Comment by p53** [comment]
i pushed another changes, now only 2 tests are failing

**Comment by p53** [comment]
all tests now fixed

**Pull request merged**
