### PR TITLE
Client resources and user permissions

### PR DESCRIPTION
**Pull request by timdrysdale**
This is a continuation of work to add non-admin methods for resources/permissions (as mentioned in issue #229)
- add the methods for creating and deleting resources by a client (ClientCreateResource, ClientDeleteResource). These complement the methods GetResourceClient, GetResourcesClient, and UpdateResourceClient which were added in PR#230.
- add methods for a client (resource server typically) to create permission ticket, as well as grant, update, get, and delete user permissions for specific resources (CreatePermissionTicket, GrantUserPermission, UpdateUserPermission, GetUserPermissions, DeleteUserPermission).

The new permissions methods are not an exact parallel to the existing admin versions. There is no obvious exact parallel between what the admin user can do with the permission methods already implemented, and what is available to resource servers via client API so I have implemented methods to offer the functionality described in the Keycloak documentation in [Authorization Services - Managing Permission Requests](https://www.keycloak.org/docs/latest/authorization_services/#_service_protection_permission_api_papi). For naming, I've used the format ```<Verb>UserPermission``` for these because they relate to users more than they do clients. I'm happy to revisit the naming of these to better suit the overall scheme. Creating a permission ticket is not granting permission to a user, ([it's an input to the RPT](https://www.keycloak.org/docs/latest/authorization_services/#_overview_terminology_permission_ticket)) so I just named it CreatePermissionTicket.

Other smaller points:

- I've added new types in ```model.go``` to support these methods, because the keycloak API has small differences in the query parameters between the API used for these newly implemented methods, and the admin API for previously implemented methods in gocloak. It would be messy to try and force these slightly differently-named fields into pre-existing models and break compartmentalisation. 

- I've left the return of the CreatePermissionsTicket as a pointer to a struct because it might be possible to get a description of the ticket from keycloak which could be returned as well, and then it would be similar to the way id token, access token, and some descriptive fields are returned when you log in.

- All methods have tests (passing). In the testing, I'm in some cases decoding the returned JWT without checking the signature because trust is not an issue - just want to confirm that the right kind of response has come back (else any valid request could pass some of the tests). I don't _think_ this will make the tests too brittle, because they shouldn't break until there are major breaking changes in the keycloak API (which would need attention anyway). 

- UpdateUserPermission adds an explicit check for 204 (StatusNoContent) so it can return a nil pointer if the update has removed the permission - this makes it easier to interpret the result than having a non-nil pointer to a struct full of nil-pointers.

- Sorry - I moved some code from my previous PR around to organise it a bit better and it has made the diff logs a bit noisy on this commit because it looks at first glance like I have messed with the pre-existing  ```<verb>Resource``` methods - I haven't.

[Issue: #229]

### CODE REVIEW

**Comment by timdrysdale** [comment]
Linting errors noted ... also I didn't update the README with the new methods ... will fix and update PR.

**Comment by timdrysdale** [comment]
All tests passing on my machine, but un-related unit test TestGocloak_UpdateRealm has failed here in CI testing.

**Comment by timdrysdale** [comment]
I've now added the methods needed to hit the [uma-policy endpoint](https://www.keycloak.org/docs/latest/authorization_services/#_service_authorization_uma_policy_api), which rounds out the three sets of methods I was initially aiming to implement against Issue #229. The next section in the keycloak docs is on RPT and that already seems to be implemented, so a good place to stop. This is ready for a review now ...

**Comment by mbecker** [comment]
Wow! Thanks!

**Review by Nerzal — APPROVED** [review]
LGTM

**Comment by Nerzal** [comment]
Thanks for your contribution! :)

**Comment by Nerzal** [comment]
tag: v7.9.0

**Comment by timdrysdale** [comment]
You're very welcome. Thanks for accepting!

**Pull request merged**
