### PR TITLE
feature: UpdateComponent

### PR DESCRIPTION
**Pull request by hrenard**
Allows to update a component.

### CODE REVIEW

**Comment by Nerzal** [comment]
Hi thank you for the contribution, could you please add a test for that function?

**Comment by hrenard** [comment]
Yes of course.

**Comment by hrenard** [comment]
Hi @Nerzal ! Sorry for the delay. I also added GetComponentByID  to facilitate the test :smile:.

**Comment by justmike1** [comment]
hey, looking forward to use this feature, commented for notification

**Comment by hrenard** [comment]
Obsolete.

**Pull request closed without merging**
